services:
  spotifyclone.api:
    image: spotifyclone.api
    build:
      context: .
      dockerfile: src/Apps/SpotifyClone.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MainDb: Host=postgres;Port=5432;Database=spotifyclone_dev;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    volumes:
      - ./storage/music:/app/wwwroot/music
      - ./storage/temp:/app/wwwroot/temp

  postgres:
    image: postgres:15
    container_name: spotifyclone-postgres
    environment:
      POSTGRES_DB: spotifyclone_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
