services:
  spotifyclone.api:
    image: spotifyclone.api
    user: root
    build:
      context: .
      dockerfile: src/Apps/SpotifyClone.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MainDb: Host=postgres;Port=5432;Database=spotifyclone_dev;Username=postgres;Password=postgres
    ports:
      - "8080:8080"
    volumes:
      - audio_data:/app/wwwroot/audio
      - temp_data:/app/wwwroot/temp

  postgres:
    image: postgres:15
    container_name: spotifyclone-postgres
    environment:
      POSTGRES_DB: spotifyclone_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: spotifyclone-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  audio_data:
  temp_data:
  postgres_data:
  minio_data:
